// const craftingRecipes = [
//     {
//         id: 'pencil_on_paper_sketch',
//         name: 'Pencil Sketch',
//         input1: 'pencil',
//         input2: 'paper',
//         output: 'pencil_sketch',
//         outputQuantity: 1,
//         consume1: 0.1,
//         consume2: 1,
//         skill: 'drawing',
//         minLevel: 1,
//         energyCost: 15,
//         value: 10,
//         unlocked: true,
//     },
//     {
//         id: 'charcoal_on_paper_sketch',
//         name: 'Charcoal Sketch',
//         input1: 'charcoal',
//         input2: 'paper',
//         output: 'charcoal_sketch',
//         outputQuantity: 1,
//         consume1: 0.5,
//         consume2: 1,
//         skill: 'drawing',
//         minLevel: 2,
//         energyCost: 20,
//         value: 25,
//         unlocked: true,
//     },
//     {
//         id: 'watercolor_on_canvas_painting', // New Watercolor Recipe
//         name: 'Watercolor Painting',
//         input1: 'watercolor',
//         input2: 'canvas',
//         output: 'watercolor_painting',
//         outputQuantity: 1,
//         consume1: 0.2, // Assuming watercolor paint is consumed partially
//         consume2: 1,   // Canvas consumed whole
//         skill: 'painting',
//         minLevel: 2,
//         energyCost: 35,
//         value: 45,
//         unlocked: true,
//     },
//     {
//         id: 'oil_paint_on_canvas_painting',
//         name: 'Oil Painting',
//         input1: 'oil_paint',
//         input2: 'canvas',
//         output: 'oil_painting',
//         outputQuantity: 1,
//         consume1: 0.2,
//         consume2: 1,
//         skill: 'painting',
//         minLevel: 3,
//         energyCost: 50,
//         value: 150,
//         unlocked: true,
//     },
//     {
//         id: 'clay_on_tools_sculpture',
//         name: 'Clay Sculpture',
//         input1: 'clay',
//         input2: 'sculpting_tools',
//         output: 'clay_sculpture',
//         outputQuantity: 1,
//         consume1: 1,
//         consume2: 0.05,
//         skill: 'sculpting',
//         minLevel: 1,
//         energyCost: 40,
//         value: 80,
//         unlocked: true,
//     }
// ];